### PR TITLE
Bugfix/client reconnect

### LINKED ISSUE #327: Requests after rpc_client reconnect fail with gate_closed_exception
**Describe the bug**
After a connection times out and `rpc_client::reconnect()` is called (as suggested by the logged exception), all future requests immediately fail, with the future containing a `seastar::gate_closed_exception`.

This seems to be caused by `rpc_client`'s gate being closed when `rpc_client::stop()` is called. Unfortunately, as of writing, `seastar::gate`s cannot be reopened once closed, so I fixed this locally by wrapping the `rpc_client`'s `dispatch_gate_` in a `std::unique_ptr`, and resetting it whenever `connect()` is invoked.  There may be a better way to solve this problem.

**To Reproduce**
1. Start an RPC server.
2. Create an RPC client with options setting a connection timeout to 1s.
3. Run the RPC client, and have the local shard sleep for 2s.  After 1s, SMF will log something like this:

  ```
[shard 0] smf - rpc_client.cc:242] Handling exception: seastar::timed_out_error (timedout)
  ```

  This line number may not match what's in the below-mentioned git hash.

  If you were to make another request at this point, the error message suggests that I should `reconnect()`.

4. Invoke the RPC client's `reconnect()` method, and in its continuation, issue an RPC to the server.  The RPC will fail.  If the exception is logged, it will be a `seastar::gate_closed_exception`.

**Expected behavior**
The RPC in step 4 should reach the server and (server willing) succeed..

**Environment Info**

OS: Ubuntu 16.04
Git hash: c7e8c58
Seastar git hash: f0c0855
Compiler: `gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1)`

### PR DESCRIPTION
**Pull request by senior7515**
Fixes #327 

Triggers new bug w/ serializing server socket flushes.

### CODE REVIEW

File: src/core/rpc_server.cc [hunk 1]
```diff
@@ -213,8 +197,35 @@ rpc_server::handle_client_connection(
...
+    return seastar::make_ready_future<>();
+  }
+
+  return seastar::with_gate(
+    reply_gate_,
+    [this, conn, context = std::move(ctx.value()), payload_size]() mutable {
+      return do_dispatch_rpc(conn, std::move(context))
+        .then([this, conn] { return cleanup_dispatch_rpc(conn); })
+        .finally(
+          [m = hist_->auto_measure(), limits = conn->limits(), payload_size] {
```
Comment (senior7515) [inline src/core/rpc_server.cc]: old comment. fix & squash

File: src/core/rpc_client.cc [hunk 2]
```diff
@@ -148,23 +155,24 @@ seastar::future<>
...
-            if (!is_conn_valid()) { return seastar::make_ready_future<>(); }
-            return rpc_envelope::send(&conn_->ostream, std::move(e))
-              .handle_exception([this](auto _) {
-                LOG_INFO("Handling exception(2): {}", _);
-                fail_outstanding_futures();
-              });
-          });
-      });
-  });
+  return seastar::with_gate(
```
Comment (senior7515) [inline src/core/rpc_client.cc]: add new function the formatter doesn't like this. sigh.

File: src/integration_tests/rpc_reconnect_with_timeout/test.json [hunk 3]
```diff
@@ -0,0 +1,4 @@
+{
+  "args": ["-c 1", "-m 2G"],
```
Comment (senior7515) [inline src/integration_tests/rpc_reconnect_with_timeout/test.json]: remove the core count.
